#!/bin/bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install more recent versions of some OS X tools
brew tap homebrew/dupes

brew install ack
brew install apple-gcc42
brew install autoconf
brew install automake
brew install bash
brew install boost
brew install cloog
brew install cmake
brew install ctags
brew install curl
brew install curl-ca-bundle
brew install daemontools
brew install dos2unix
brew install elasticsearch
brew install encfs
brew install encfsmacosxfuse
brew install freetype
brew install gdbm
brew install gettext
brew install gfortran
brew install git
brew install gmp
brew install gnupg
brew install go
brew install graphviz
brew install heroku-toolbelt
brew install imagemagick
brew install isl
brew install jpeg
brew install jq
brew install leiningen
brew install libevent
brew install libgpg-error
brew install libksba
brew install libmpc
brew install libpng
brew install libtool
brew install libxml2
brew install libxslt
brew install libyaml
brew install matplotlib
brew install memcached
brew install mercurial
brew install mpfr
brew install nginx
brew install numpy
brew install openssl
brew install ossp-uuid
brew install osxfuse
brew install pbzip2
brew install pcre
brew install percona-server
brew install phantomjs
brew install pidof
brew install pkg-config
brew install postgresql
brew install pv
brew install python
brew install qt
brew install rbenv
brew install readline
brew install redis
brew install rlog
brew install scipy
brew install scons
brew install suite-sparse
brew install swig
brew install tbb
brew install tree
brew install wget
brew install wkhtmltopdf

# Change login shell to the homebrew-installed bash
sudo dscl . -change $HOME UserShell /bin/bash /usr/local/bin/bash

# If ^^^ has already been run once, it will throw this harmless error:
#   <main> attribute status: eDSAttributeNotFound
#   <dscl_cmd> DS Error: -14134 (eDSAttributeNotFound)

# Remove outdated versions from the cellar
brew cleanup
